### ISSUE TITLE
sqlite connect

### ISSUE THREAD

**Issue by raisiqueira** [balping/ticketit-app#5]
I installed this package, however I selected sqlite, and it returns the following error
```
Database file created at /var/www/app/database/database.sqlite
Checking database connection...
Could not connect to database.
```

**Comment by balping** [comment]
`apt-get install php-sqlite3` ? (Or any equivalent on your system)

**Comment by raisiqueira** [comment]
Already installed. I'm running with Docker.
```
version: '2'

services:

  mysql:
    image: mariadb:latest
    container_name: mysql-ticketit
    volumes:
      - "./.datadb:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ticketit
      - MYSQL_DATABASE=ticketit
      - MYSQL_USER=ticketit
      - MYSQL_PASSWORD=ticketit

  cache:
    image: ambientum/redis:3.2
    container_name: cache-ticketit
    command: --appendonly yes
    volumes:
      - redis-data-tickeit:/data
    restart: always

  app:
    image: ambientum/php:7.1-nginx
    container_name: app-ticketit
    volumes:
      - .:/var/www/app
    ports:
      - "8083:8080"
    restart: always
    links:
      - mysql

volumes:
  redis-data-tickeit:
    driver: local
```
